//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estadistica
    {
        public int EstadisticaID { get; set; }
        public int UsuarioID { get; set; }
        public int PreguntasRealizadas { get; set; }
        public int RespuestasRealizadas { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
