//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuesta
    {
        public int RespuestaID { get; set; }
        public string UsuarioID { get; set; }
        public int PreguntaID { get; set; }
        public string ContenidoRespuesta { get; set; }
    
        public virtual Pregunta Pregunta { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
